theme: jekyll-theme-hacker
title: Quinns GitHub Branch of the main site
description: Bookmark this to keep an eye on my project updates!

## Welcome to my Git Branch of my website!

## Projects:

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Windows Activation Dodger

Remove your watermark like the dishonest swine you are!

How to run

Step 1 Run ActivationDodger.bat (OR if you downloaded the executable installer run that first)

Step 2 Restart pc.

Step 3 (Optional) Make a shortcut of Wrapper.vbs and move it to the Windows startup folder (The default directory will be displayed when the bat file is run). Make sure you dont move ActivationDodger, DirCpy or Appdata to the startup because the Wrapper shortcut will automatically trace the directory.

#DISCLAIMER: THIS PROGRAM WAS BUILD FOR WINDOWS 10. IF YOU WOULD LIKE TO BECOME A TESTER FOR THE PROGRAM JOIN MY DISCORD AND HELP TEST THE PROGRAM ON DIFFERENT SYSTEMS!

Discord invite: https://discord.gg/GTwQr4vYfS REPORT ALL BUGS AND ISSUES ON THE DISCORD SERVER

Compatibility:

Architecture: 32Bit + 64 Bit

Operating systems: Windows 10

Minimum specs: You can probably run it on a potato

Level of computer knowlege: If you can read simple instructions you'll be just fine

"Project Link: https://github.com/qmlhunter/Windows-Activation-Dodger"

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Bootforge-oem
Unlock your Android device's bootloader in a few clicks!

(Download the whole folder it contains all prerequisites preinstalled)
Run the .bat file corresponding with your device's age!

Join my discord for project suggestions and bug reporting!

The link is as follows: https://discord.gg/GTwQr4vYfS

"Project Link: https://github.com/qmlhunter/bootforge-oem"

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

## QuinnConvert
Convert Text into various formats and vice versa! (Python)

Currently supported formats (Subject to change):

Base16
Base32
Base 64
Base85
Hex

Discord invite: https://discord.gg/GTwQr4vYfS REPORT ALL BUGS AND ISSUES ON THE DISCORD SERVER

"Project Link: https://github.com/qmlhunter/QuinnConvert"

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

# QuinntavichBot
A fairly simple bot I made including an economy system and a birthday system!

## Instructions 

Change line 579 to the path to the cogs folder in the bot folder

Change lines 1459 + 624 + 641 to your Giphy API Key

Change last line to your discord Bot API Key

"Project Link: https://github.com/qmlhunter/QuinntavichBot"

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------



