<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body {
width: 800px;
max-width: 100%;
}
<h1>Welcome</h1>
<p>Autoinstall begins now</p>
<p><a href="https://qmlhunter.github.io/">Back to main page.</a>
</style>
<script>
var ua = navigator.userAgent;
var fwVersion = ua.substring(ua.indexOf("5.0 (") + 19, ua.indexOf(") Apple"));
window.location.href = 'https://qmlhunter.github.io/quinnhen/' + fwVersion + '/index.html';
</script>
</head>
<noscript>
Bro where's ur javascript?????
</noscript>
</html>
